# Generated by Django 5.2.8 on 2025-11-21 00:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Brief title describing the purchase request', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the purchase request')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount for the purchase request', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current status of the purchase request', max_length=16)),
                ('version', models.PositiveIntegerField(default=0, help_text='Version field for optimistic locking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when request was fully approved', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this purchase request', on_delete=django.db.models.deletion.PROTECT, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('last_approved_by', models.ForeignKey(blank=True, help_text='User who provided the final approval', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('proforma', models.ForeignKey(blank=True, help_text='Associated proforma document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='documents.document')),
            ],
            options={
                'db_table': 'purchases_purchaserequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(help_text='Unique purchase order number', max_length=50, unique=True)),
                ('vendor', models.CharField(help_text='Vendor name extracted from proforma or manually entered', max_length=255)),
                ('vendor_contact', models.TextField(blank=True, help_text='Vendor contact information')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total purchase order amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Vendor'), ('ACKNOWLEDGED', 'Acknowledged by Vendor'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current status of the purchase order', max_length=16)),
                ('data', models.JSONField(default=dict, help_text='Structured PO data including items, terms, and metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when PO was sent to vendor', null=True)),
                ('pdf_document', models.ForeignKey(blank=True, help_text='Generated PDF document for this PO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_pdf', to='documents.document')),
                ('request', models.OneToOneField(help_text='Original purchase request', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='purchases.purchaserequest')),
            ],
            options={
                'db_table': 'purchases_purchaseorder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')], help_text='Approval level (1 or 2)')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], help_text='Approval decision', max_length=16)),
                ('comment', models.TextField(blank=True, help_text='Optional comment explaining the decision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(help_text='User who made the approval decision', on_delete=django.db.models.deletion.PROTECT, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(help_text='Purchase request being approved', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='purchases.purchaserequest')),
            ],
            options={
                'db_table': 'purchases_approval',
                'ordering': ['level', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or description of the item', max_length=255)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of items requested', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, help_text='Additional description or specifications')),
                ('unit_of_measure', models.CharField(blank=True, help_text='Unit of measure (e.g., pieces, kg, hours)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(help_text='Purchase request this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaserequest')),
            ],
            options={
                'db_table': 'purchases_requestitem',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status'], name='idx_pr_status'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['created_by'], name='idx_pr_created_by'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['amount'], name='idx_pr_amount'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['created_at'], name='idx_pr_created_at'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', 'created_at'], name='idx_pr_status_created'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='idx_po_number'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['vendor'], name='idx_po_vendor'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='idx_po_status'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['created_at'], name='idx_po_created_at'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['total'], name='idx_po_total'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['request'], name='idx_approval_request'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['approver'], name='idx_approval_approver'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['level'], name='idx_approval_level'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['decision'], name='idx_approval_decision'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['created_at'], name='idx_approval_created_at'),
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.UniqueConstraint(fields=('request', 'level'), name='unique_approval_per_request_level'),
        ),
        migrations.AddIndex(
            model_name='requestitem',
            index=models.Index(fields=['request'], name='idx_request_item_request'),
        ),
        migrations.AddIndex(
            model_name='requestitem',
            index=models.Index(fields=['name'], name='idx_request_item_name'),
        ),
    ]
