# Generated by Django 5.2.8 on 2025-11-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured PO data including items, terms, and metadata'),
        ),
    ]
