# Generated by Django 5.2.8 on 2025-11-22 12:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchaseorder_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='data',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='pdf_document',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional structured data for PO'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Vendor'), ('ACKNOWLEDGED', 'Acknowledged by Vendor'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount for the purchase request', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterModelTable(
            name='purchaseorder',
            table=None,
        ),
    ]
