# Generated by Django 5.2.8 on 2025-11-22 13:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_remove_purchaseorder_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount for the purchase request', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
