# Generated by Django 5.2.8 on 2025-11-21 00:03

import django.core.validators
import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Document file (PDF or image formats)', upload_to=documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'tiff', 'bmp'])])),
                ('original_filename', models.CharField(help_text='Original filename when uploaded', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_hash', models.CharField(help_text='SHA-256 hash of file content for deduplication', max_length=64, unique=True)),
                ('doc_type', models.CharField(choices=[('PROFORMA', 'Proforma Invoice'), ('RECEIPT', 'Receipt'), ('PO', 'Purchase Order'), ('INVOICE', 'Invoice'), ('CONTRACT', 'Contract'), ('OTHER', 'Other')], help_text='Type of document', max_length=16)),
                ('title', models.CharField(blank=True, help_text='Document title or description', max_length=255)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Processing Completed'), ('FAILED', 'Processing Failed'), ('SKIPPED', 'Processing Skipped')], default='PENDING', help_text='Status of document processing', max_length=20)),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted from document via OCR', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured metadata extracted from document', null=True)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when processing completed', null=True)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this document', on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doc_type'], name='idx_document_doc_type'), models.Index(fields=['uploaded_by'], name='idx_document_uploaded_by'), models.Index(fields=['processing_status'], name='idx_document_processing_status'), models.Index(fields=['created_at'], name='idx_document_created_at'), models.Index(fields=['file_hash'], name='idx_document_file_hash')],
            },
        ),
    ]
